### ISSUE TITLE
Add Cardano

### ISSUE THREAD

**Issue by lemastero** [xenowits/nakomoto-coefficient-calculator#1]
Hi
It would be nice to include Cardanao - top PoS [according to coinmarketcap](https://coinmarketcap.com/view/pos/).
[Here](https://datastudio.google.com/u/0/reporting/3136c55b-635e-4f46-8e4b-b8ab54f2d460/page/p_9vyfu6gorc) nakamoto-coefficient is 22 (I believe MAV == nakamoto coefficient).

**Comment by xenowits** [comment]
Hi @lemastero . I have kind of dropped working on this but if anyone wants to contribute, feel free to pick it up. I can help with the structure and setting up of stuff

**Comment by lemastero** [comment]
Hi @xenowits do you have some code that one could use and build on top of it?
