### ISSUE TITLE
Pulsechain: a reliable project?

### ISSUE THREAD

**Issue by alfredonodo** [xenowits/nakomoto-coefficient-calculator#49]
Hello,
I have some doubts about this project. According to [CMC](https://coinmarketcap.com/currencies/pulsechain/) and [CG](https://www.coingecko.com/en/coins/pulsechain) it exists since May 2023, but it has almost zero daily volume (99% in an unknown exchange) and the total circulating and supply are not verified (self reported).
Also, it is impossible to find the whitepaper to understand how it works. All we know is that it is an Ethereum hardfork that [Certik](https://skynet.certik.com/projects/pulsechain) gave a grade of C (among the lowest ever).
According to their website there are about [50k validators](https://beacon.pulsechain.com/), but it is not possible to verify what Nakamoto coefficient is without knowing the consensus protocol.
In my opinion, the project should be removed until more clarity is provided.

**Comment by yngwiewylde** [comment]
Zero daily volume? Except for the $millions daily here -> https://dexscreener.com/pulsechain  Supply is listed here --> https://gopulse.com/ How it works? What is the consensus protocol? It is a hard fork of Ethereum so the consensus protocol is exactly the same as Ethereum. Check out https://launchpad.mypinata.cloud/ipfs/bafybeigj2mn6ovjbfme5hu2wq7boby3gurz35k6fbthwihz3lbgxayegr4/#/en/ or get the latest IPFS link from https://launchpad.pulsechain.com/

**Comment by alfredonodo** [comment]
@yngwiewylde 
Thank you for your reply. As I wrote before, according to CMC and CG the circulating supply and market capitalisation are not verified. In particular according to [CMC](https://support.coinmarketcap.com/hc/en-us/articles/360043836851-Ranking-Cryptoasset-Exchange-) all projects above position 200 do not fulfil their requirements and therefore one has to be careful. Pulsechain data are self-reported and not third party verified, so the project is not reliable.
The same goes for volumes, according to [CMC](https://coinmarketcap.com/currencies/pulsechain/#Markets) about 6.5k $ is on a single exchange SafeTrade. According to [CG](https://www.coingecko.com/en/coins/pulsechain#markets) about 40k $ is on three exchanges SafeTrade, Kanga and Bitcointry. Why are CMC and CG not reporting DexScreener data?
Finally, I understand that to become a validator on pulsechain you need 32M coins (instead of 32 as on ethereum), although there is no whitepaper.
According to this page from your [link](https://gopulse.com/validators) 55% of validators are inside validatorstore.com (is it a staking pool like on ethereum?). If so, the Nakomoto coefficient is much reduced to less than 10, as on ethereum.

**Comment by yngwiewylde** [comment]
@alfredonodo You're welcome. CMC have a history of keeping the HEX (same founder) Market Cap ranking at position 201 for 3+ years despite the price moving up 10,000x and then down 99%. That is obviously not possible hence I would not trust the CMC market cap data/ranking since it's provably manipulated. 

You seem a bit confused to think that the only volume a chain can have is that which is on centralized exchanges (the ones you mentioned). I showed you the daily volume in the $millions on https://dexscreener.com/pulsechain . DEXs are a massive part of crypto, there is even more volume on other PulseChain DEXs like https://phux.io/#/ and others that aren't listed on dexscreener too. 

CMC and CG are reporting the Dexscreener data, you're just not looking in the right place. PulseX is just one DEX on PulseChain but look here -> https://coinmarketcap.com/exchanges/pulsex/ and https://www.coingecko.com/en/exchanges/pulsex . 

With regard to your question about validatorstore.com -- no, it's not a staking pool. It's a store where you can buy NUC hardware with prebuilt Validator software installed so you can run your own node from home. The PulseChain Nakomoto coefficient is currently at 6. I hope I have answered all of your questions.

**Comment by alfredonodo** [comment]
> CMC have a history of keeping the HEX (same founder) Market Cap ranking at position 201 for 3+ years despite the price moving up 10,000x and then down 99%. That is obviously not possible hence I would not trust the CMC market cap data/ranking since it's provably manipulated.

The founder of Hex seems to be a [scammer](https://www.reuters.com/world/us/us-charges-youtuber-richard-heart-with-fraud-related-unregistered-crypto-2023-07-31/), so I honestly trust CMC more.

> You seem a bit confused to think that the only volume a chain can have is that which is on centralized exchanges (the ones you mentioned). I showed you the daily volume in the $millions on https://dexscreener.com/pulsechain . DEXs are a massive part of crypto, there is even more volume on other PulseChain DEXs like https://phux.io/#/ and others that aren't listed on dexscreener too.
> 
> CMC and CG are reporting the Dexscreener data, you're just not looking in the right place. PulseX is just one DEX on PulseChain but look here -> https://coinmarketcap.com/exchanges/pulsex/ and https://www.coingecko.com/en/exchanges/pulsex .

Thank you, but read carefully what I wrote. CMC and CG report both CEX and DEX, pulsechain (PLS) has the volumes reported in my previous post. What you reported are the volumes on the pulsechain blockchain and they do not refer to PLS, but to WPLS [CMC](https://coinmarketcap.com/currencies/wrapped-pulse/#Markets) and [CG](https://www.coingecko.com/en/coins/wrapped-pulse#markets).

> With regard to your question about validatorstore.com -- no, it's not a staking pool. It's a store where you can buy NUC hardware with prebuilt Validator software installed so you can run your own node from home. The PulseChain Nakomoto coefficient is currently at 6. I hope I have answered all of your questions.

This number is more plausible than the over 10k I saw a few days ago.

**Comment by yngwiewylde** [comment]
WPLS is just wrapped PLS. They're equivalent 1:1. It's just like how 1 WETH = 1 ETH on Ethereum. DEXs wrap native ETH into an ERC20 (WETH) to do the swap on-chain.

**Comment by alfredonodo** [comment]
> WPLS is just wrapped PLS. They're equivalent 1:1. It's just like how 1 WETH = 1 ETH on Ethereum. DEXs wrap native ETH into an ERC20 (WETH) to do the swap on-chain.

Yes and no. A wrapped coin is not exactly the same as the original coin. As you say it is true that they are exchanged 1:1, but it is also true that it depends on another blockchain. So if the latter has problems the peg is compromised.
However, it is very strange that the volume of the wrapped coin is greater than that of the original coin. I cannot remember any other examples of similar coins.
